/* =========================================================
   English Around You · 场景对话句库
   格式：["角色: 英文","角色：中文"]，连续两条为一轮对话。
   第一人称用 Me:（我：），朗读时自动忽略角色名，只读句子。
   注意：新增句子请追加在场景末尾，收藏用「场景id:序号」定位。
   ========================================================= */

const CATS = [
  { id: 'home',      emoji: '🏠', zh: '居家生活' },
  { id: 'kitchen',   emoji: '🍳', zh: '厨房三餐' },
  { id: 'outing',    emoji: '🚗', zh: '出行通勤' },
  { id: 'shopping',  emoji: '🛍️', zh: '购物消费' },
  { id: 'parenting', emoji: '👨‍👩‍👧‍👦', zh: '亲子育儿' },
  { id: 'fitness',   emoji: '💪', zh: '运动健身' },
  { id: 'health',    emoji: '💊', zh: '健康就医' },
  { id: 'errands',   emoji: '🏢', zh: '办事业务' },
  { id: 'social',    emoji: '🎉', zh: '社交聚会' },
  { id: 'leisure',   emoji: '🎬', zh: '休闲娱乐' },
  { id: 'work',      emoji: '💼', zh: '职场办公' },
  { id: 'trip',      emoji: '🧳', zh: '短途出游' },
  { id: 'oops',      emoji: '🌧️', zh: '突发状况' },
  { id: 'online',    emoji: '💻', zh: '线上沟通' },
];

const SCENARIOS = [
  /* ================= 居家生活 ================= */
  { id: 'home-wakeup', cat: 'home', emoji: '🌅', zh: '早晨起床', en: 'Waking Up', sents: [
    ["Me: Honey, it's seven. Time to get up.", "我：亲爱的，七点了，该起床了。"],
    ["Honey: Just five more minutes, please.", "亲爱的：就让我再睡五分钟嘛。"],
    ["Me: Come on, kids! Wake up, sleepyheads!", "我：快起来啦，小懒虫们！"],
    ["Kids: Mom, it's still early!", "孩子们：妈妈，还早呢！"],
    ["Me: Emma, did you sleep well?", "我：Emma，昨晚睡得好吗？"],
    ["Emma: Yes, but I had a strange dream.", "Emma：挺好，就是我做了个奇怪的梦。"],
    ["Me: Leo, get out of bed now, okay?", "我：Leo，现在就起床，好不好？"],
    ["Leo: Okay, okay... I'm up!", "Leo：好啦好啦……我起来了！"],
    ["Me: Looks like rain today. Grab your jackets.", "我：今天看着要下雨，把外套带上。"],
    ["Emma: Got it! Where's my umbrella?", "Emma：知道啦！我的伞在哪儿？"],
    ["Me: Today's plan: school, then swim class.", "我：今天安排：上学，然后游泳课。"],
    ["Kids: Yay! Swimming!", "孩子们：耶！游泳课！"],
  ]},
  { id: 'home-leaving', cat: 'home', emoji: '🚪', zh: '出门前准备', en: 'Before Leaving Home', sents: [
    ["Me: Kids, go brush your teeth. Quick!", "我：孩子们，快去刷牙，快点！"],
    ["Emma: I already did! Leo hasn't.", "Emma：我刷过了！Leo 还没。"],
    ["Me: Leo, wash your face, buddy.", "我：Leo，洗把脸，小伙子。"],
    ["Leo: Mom, where's my other shoe?", "Leo：妈妈，我另一只鞋呢？"],
    ["Me: Have you seen my keys? I can't find them.", "我：你看到我的钥匙了吗？找不到了。"],
    ["Honey: Check the sofa. You left them there last night.", "亲爱的：看看沙发上，你昨晚落在那儿了。"],
    ["Me: Found them! Now where's my phone?", "我：找到了！那我手机呢？"],
    ["Emma: It's in your hand, Mom!", "Emma：不就在你手里嘛，妈妈！"],
    ["Me: Umbrellas, water bottles, jackets... all set?", "我：雨伞、水杯、外套……都带齐了吗？"],
    ["Kids: Yes, Mom! Let's go!", "孩子们：都带好啦，妈妈！走吧！"],
    ["Me: Wait, the lights! I'm turning them off.", "我：等等，灯还没关，我关一下。"],
    ["Honey: I'll wait in the car.", "亲爱的：我在车里等你。"],
  ]},
  { id: 'home-chores', cat: 'home', emoji: '🧹', zh: '家务分工', en: 'Splitting Chores', sents: [
    ["Me: Okay, let's split the chores this weekend.", "我：好啦，这周末的家务咱们分分工。"],
    ["Honey: Sure. I'll take out the trash.", "亲爱的：行，我倒垃圾。"],
    ["Me: Great. I'll mop the floors after lunch.", "我：好，我午饭后拖地。"],
    ["Honey: And the dishes?", "亲爱的：那碗谁洗？"],
    ["Me: The kids can dry the dishes. Right, kids?", "我：孩子们负责把碗擦干，对吧孩子们？"],
    ["Kids: Aww, do we have to?", "孩子们：啊，非做不可吗？"],
    ["Me: Yes! And tidy up your room before dinner.", "我：必须的！还有晚饭前把房间收拾好。"],
    ["Emma: My room is pretty clean already.", "Emma：我的房间已经挺干净的了。"],
    ["Me: Leo, your toys are everywhere. Pick them up.", "我：Leo，你的玩具扔得到处都是，收一收。"],
    ["Leo: Okay... I'll do it in five minutes.", "Leo：好吧……我五分钟后就收。"],
    ["Me: No \"five minutes.\" Now, please.", "我：不许说“五分钟后”，现在就收。"],
    ["Honey: I'll help you, little man.", "亲爱的：我来帮你吧，小家伙。"],
  ]},
  { id: 'home-chat', cat: 'home', emoji: '☕', zh: '居家闲聊', en: 'Evening Chat', sents: [
    ["Me: How was your day, Honey?", "我：亲爱的，今天过得怎么样？"],
    ["Honey: Not bad. The meeting ran way too long.", "亲爱的：还行，就是那个会开得太久了。"],
    ["Me: Again? Your boss loves meetings.", "我：又这样？你们老板真爱开会。"],
    ["Honey: Tell me about it. How was your day?", "亲爱的：可不是嘛。你今天呢？"],
    ["Me: Pretty good. I ran into an old friend at the store.", "我：挺不错的，我在超市碰到一个老朋友。"],
    ["Honey: Oh? Who was it?", "亲爱的：哦？是谁呀？"],
    ["Me: Remember Lily? We used to work together.", "我：还记得 Lily 吗？我们以前一起上过班。"],
    ["Honey: Of course! How is she doing?", "亲爱的：当然记得！她最近怎么样？"],
    ["Me: Great. She just moved back to the city.", "我：挺好的，她刚搬回这个城市。"],
    ["Honey: We should have her over for dinner.", "亲爱的：哪天请她来家里吃饭吧。"],
    ["Me: Good idea. I'll text her this weekend.", "我：好主意，这周末我给她发消息。"],
    ["Honey: Perfect.", "亲爱的：就这么定了。"],
  ]},
  { id: 'home-appliance', cat: 'home', emoji: '🔧', zh: '家电小故障', en: 'Appliance Problems', sents: [
    ["Me: The living room light keeps flickering.", "我：客厅的灯一闪一闪的。"],
    ["Honey: Yeah, I noticed. The bulb might be loose.", "亲爱的：我注意到了，可能是灯泡松了。"],
    ["Me: I tried tightening it, but it's still flickering.", "我：我拧紧了，可它还是闪。"],
    ["Honey: Then let's get a new bulb this weekend.", "亲爱的：那这周末买个新灯泡吧。"],
    ["Me: And the AC isn't cooling well either.", "我：还有空调也不太制冷了。"],
    ["Honey: Did you clean the filter?", "亲爱的：你洗过滤网了吗？"],
    ["Me: Oh, right. I forgot all about it.", "我：哦对，我完全忘了这茬。"],
    ["Honey: Clean it first. If it's still weak, we'll call for service.", "亲爱的：先洗洗看，要是还不行，咱们就叫人上门修。"],
    ["Me: Deal. I'll do it tomorrow morning.", "我：行，我明早洗。"],
    ["Honey: Great. Fingers crossed it works.", "亲爱的：好，希望洗了能管用。"],
  ]},
  { id: 'home-parcels', cat: 'home', emoji: '📦', zh: '拆快递包裹', en: 'Opening Packages', sents: [
    ["Emma: Mom, a package came for you!", "Emma：妈妈，有你的快递！"],
    ["Me: Oh good, it's my new running shoes.", "我：太好了，是我买的新跑鞋。"],
    ["Leo: Can I open it? Please?", "Leo：我能拆吗？求求你啦？"],
    ["Me: Sure, be careful with the scissors.", "我：可以，剪刀小心点用。"],
    ["Emma: Wow, they're so cool! Try them on!", "Emma：哇，好酷啊！快试穿一下！"],
    ["Me: Nice fit. Very comfortable.", "我：挺合脚的，很舒服。"],
    ["Leo: Is it my turn? Do I have a package?", "Leo：轮到我了吗？有我的快递吗？"],
    ["Me: Yours is coming tomorrow, little guy.", "我：你的明天才到，小家伙。"],
    ["Emma: Oh, this one's Dad's. It's really heavy!", "Emma：哦，这个是爸爸的，好沉呀！"],
    ["Me: He ordered a coffee maker. Let's not open his.", "我：他买了个咖啡机，咱们别拆他的。"],
  ]},
  { id: 'home-night', cat: 'home', emoji: '🌃', zh: '夜晚睡前', en: 'End of the Day', sents: [
    ["Me: Finally, some quiet time. How was today?", "我：终于安静会儿了。今天过得怎么样？"],
    ["Honey: Busy but good. The kids had fun at the park.", "亲爱的：忙但挺开心，孩子们在公园玩得很尽兴。"],
    ["Me: Yeah. Emma's getting really brave on the slide.", "我：是啊，Emma 现在滑滑梯可勇敢了。"],
    ["Honey: And Leo made a new friend today.", "亲爱的：Leo 今天还交了个新朋友。"],
    ["Me: That's sweet. Time really flies.", "我：真不错，时间过得真快呀。"],
    ["Honey: It does. By the way, we need milk and eggs.", "亲爱的：可不是嘛。对了，家里要买牛奶和鸡蛋了。"],
    ["Me: I'll add them to the shopping list.", "我：我加到购物清单里。"],
    ["Honey: Good. Anything else to plan for this week?", "亲爱的：好。这周还有什么要安排的吗？"],
    ["Me: The kids' school photos are due on Friday.", "我：孩子们的学校照片周五前要交。"],
    ["Honey: Noted. I'll handle it. Now, get some rest.", "亲爱的：记下了，我来处理。行了，早点休息吧。"],
  ]},

  /* ================= 厨房三餐 ================= */
  { id: 'kitchen-dinnerplan', cat: 'kitchen', emoji: '🍲', zh: '计划晚餐', en: 'Planning Dinner', sents: [
    ["Me: What should we make for dinner tonight?", "我：今晚咱们做什么吃？"],
    ["Honey: Let's see what's in the fridge first.", "亲爱的：先看看冰箱里还有什么吧。"],
    ["Me: We have some chicken, eggs, and two tomatoes.", "我：有鸡肉、鸡蛋，还有两个西红柿。"],
    ["Honey: How about tomato and egg soup and fried chicken?", "亲爱的：西红柿鸡蛋汤再加个香煎鸡肉怎么样？"],
    ["Me: Sounds good. Do we have any vegetables left?", "我：行啊。还有青菜吗？"],
    ["Honey: Just a little broccoli. It's getting old.", "亲爱的：就剩一点西兰花了，都有点不新鲜了。"],
    ["Me: Then let's cook it today. Waste not, want not.", "我：那今天把它炒了吧，别浪费。"],
    ["Honey: Agreed. I'll make rice. You do the soup?", "亲爱的：同意。我焖饭，你做汤？"],
    ["Me: Deal. Dinner will be ready in half an hour.", "我：一言为定，半小时后开饭。"],
    ["Honey: I'll set the table.", "亲爱的：我来摆碗筷。"],
  ]},
  { id: 'kitchen-cooking', cat: 'kitchen', emoji: '🍳', zh: '做饭协作', en: 'Cooking Together', sents: [
    ["Me: Honey, can you give me a hand?", "我：亲爱的，来搭把手行吗？"],
    ["Honey: Sure, what do you need?", "亲爱的：当然，需要我干啥？"],
    ["Me: Wash the broccoli and cut the tomatoes, please.", "我：把西兰花洗一下，西红柿切了。"],
    ["Honey: On it. Where's the cutting board?", "亲爱的：好嘞。砧板在哪儿？"],
    ["Me: In the second drawer. Careful with the knife.", "我：第二个抽屉里。用刀小心点。"],
    ["Honey: Got it. Done! What's next?", "亲爱的：好啦，搞定！接下来干嘛？"],
    ["Me: Can you crack three eggs into this bowl?", "我：往这个碗里打三个鸡蛋。"],
    ["Honey: Sure. Want me to beat them?", "亲爱的：行，要搅散吗？"],
    ["Me: Yes, please. I'll start the soup.", "我：要，谢谢。我开始烧汤了。"],
    ["Honey: This smells amazing already.", "亲爱的：闻着就已经很香了。"],
    ["Me: Almost done. Call the kids to wash their hands.", "我：快好了，叫孩子们洗手准备吃饭。"],
    ["Honey: Kids! Dinner in five minutes!", "亲爱的：孩子们！五分钟后开饭啦！"],
  ]},
  { id: 'kitchen-table', cat: 'kitchen', emoji: '🍚', zh: '饭桌聊天', en: 'At the Dinner Table', sents: [
    ["Me: Come on, everyone. Dinner's ready!", "我：来来来，开饭啦！"],
    ["Kids: Yay! What are we having?", "孩子们：耶！今天吃什么？"],
    ["Me: Tomato and egg soup, fried chicken, and broccoli.", "我：西红柿鸡蛋汤、香煎鸡肉，还有西兰花。"],
    ["Leo: Broccoli? I don't like broccoli!", "Leo：西兰花？我不喜欢吃西兰花！"],
    ["Me: Try a little first. It's good for you.", "我：先尝一小口，对你身体好。"],
    ["Leo: ...Fine. Hmm, it's actually okay.", "Leo：……好吧。嗯，其实还行。"],
    ["Me: See? So, Emma, how was school today?", "我：看吧。对了 Emma，今天学校怎么样？"],
    ["Emma: Good! I got a star in English class.", "Emma：很好！我英语课得了一颗星。"],
    ["Me: That's wonderful! We're so proud of you.", "我：太棒了！我们真为你骄傲。"],
    ["Honey: Nice work, Emma. Keep it up!", "亲爱的：真不错 Emma，继续保持！"],
    ["Emma: Thanks, Mom and Dad! The soup is yummy.", "Emma：谢谢爸爸妈妈！这个汤好好喝。"],
    ["Me: Glad you like it. Eat up, everyone.", "我：喜欢就多喝点，大家快吃吧。"],
  ]},
  { id: 'kitchen-takeout', cat: 'kitchen', emoji: '🥡', zh: '商量点外卖', en: 'Ordering Takeout', sents: [
    ["Me: I'm too tired to cook tonight. Takeout?", "我：今晚太累不想做饭了，点外卖吧？"],
    ["Honey: Good idea. What are you craving?", "亲爱的：好呀，你想吃什么？"],
    ["Me: How about hot pot? Or dumplings?", "我：火锅怎么样？或者饺子？"],
    ["Honey: Hmm, the kids want burgers, I think.", "亲爱的：嗯，孩子们好像想吃汉堡。"],
    ["Me: Again? We had burgers last week.", "我：又吃汉堡？上周才吃过。"],
    ["Honey: True. Let's do dumplings then. The kids like them too.", "亲爱的：也是。那吃饺子吧，孩子们也爱吃。"],
    ["Me: Deal. Which restaurant? The one on Main Street?", "我：行。点哪家？主街那家？"],
    ["Honey: Sure, and add an extra order of dumplings.", "亲爱的：就那家，再多加一份饺子。"],
    ["Me: Done! It'll be here in about forty minutes.", "我：点好了！大概四十分钟送到。"],
    ["Honey: Great. I'll get the drinks ready.", "亲爱的：好，我来准备饮料。"],
  ]},
  { id: 'kitchen-aftermeal', cat: 'kitchen', emoji: '🧽', zh: '饭后处理', en: 'After Dinner', sents: [
    ["Me: Good dinner, everyone. Who's doing the dishes?", "我：晚饭吃得不错。谁来洗碗？"],
    ["Kids: Rock, paper, scissors!", "孩子们：石头剪刀布！"],
    ["Emma: I win! So Leo washes, I dry.", "Emma：我赢啦！那 Leo 洗，我擦。"],
    ["Leo: No fair! Best two out of three?", "Leo：不公平！三局两胜行不行？"],
    ["Me: No way. You lost, buddy. Wash up.", "我：没门儿，输了就是输了，快去洗。"],
    ["Leo: Okay... but Emma has to dry fast.", "Leo：好吧……但 Emma 得快点擦。"],
    ["Me: Honey, can you wipe the table?", "我：亲爱的，你擦一下桌子行吗？"],
    ["Honey: Sure. And you put away the leftovers?", "亲爱的：行。你把剩菜收进冰箱？"],
    ["Me: Already on it. Teamwork makes it quick.", "我：已经在弄了。齐心协力就是快。"],
    ["Kids: All done! Can we watch TV now?", "孩子们：弄完啦！现在能看电视了吗？"],
  ]},
  { id: 'kitchen-groceries', cat: 'kitchen', emoji: '📝', zh: '准备采购', en: 'Grocery List', sents: [
    ["Me: We're almost out of groceries. Let's make a list.", "我：家里菜快吃完了，列个买菜清单吧。"],
    ["Honey: Okay. Milk and eggs first.", "亲爱的：好，先写牛奶和鸡蛋。"],
    ["Me: Some chicken, fish, and a piece of beef.", "我：再来点鸡肉、鱼，还有一块牛肉。"],
    ["Honey: Don't forget vegetables. The kids need greens.", "亲爱的：别忘了蔬菜，孩子们得吃青菜。"],
    ["Me: Broccoli, carrots, and tomatoes. Got it.", "我：西兰花、胡萝卜、西红柿。记上了。"],
    ["Honey: Fruit too. Apples and bananas?", "亲爱的：水果也来点，苹果和香蕉？"],
    ["Me: Sure. And Leo's yogurt. He loves that.", "我：行。还有 Leo 的酸奶，他可爱喝了。"],
    ["Honey: Right. Anything for breakfast?", "亲爱的：对。早餐的食材要不要？"],
    ["Me: Bread and jam. That's it, I think.", "我：面包和果酱。差不多了吧。"],
    ["Honey: Great. We'll go to the market tomorrow morning.", "亲爱的：好，明天早上去菜市场。"],
  ]},

  /* ================= 出行通勤 ================= */
  { id: 'outing-drive', cat: 'outing', emoji: '🚙', zh: '自驾出门', en: 'Driving Out', sents: [
    ["Me: Ready to go? Buckle up, everyone.", "我：准备出发啦，大家都系好安全带。"],
    ["Kids: Done! Can we listen to songs?", "孩子们：系好啦！能听歌吗？"],
    ["Me: Sure. Let me set the GPS first.", "我：可以。我先设一下导航。"],
    ["Honey: It's about half an hour. Traffic looks heavy.", "亲爱的：大概半小时，看着有点堵。"],
    ["Me: Then let's take the main road instead.", "我：那咱们改走大路吧。"],
    ["Honey: Good call. It should be faster.", "亲爱的：明智，那样应该快点。"],
    ["Me: Kids, no fighting in the back seat, okay?", "我：孩子们，后座不许打闹，听到没？"],
    ["Kids: Okay, Mom...", "孩子们：知道啦，妈妈……"],
    ["Me: Alright, off we go.", "我：好嘞，出发。"],
    ["Honey: Drive safe.", "亲爱的：开慢点，注意安全。"],
  ]},
  { id: 'outing-ride', cat: 'outing', emoji: '📱', zh: '打网约车', en: 'Ride Hailing', sents: [
    ["Me: Hi, I'm going to Garden Mall, please.", "我：你好，我去花园购物中心。"],
    ["Driver: Sure. Hop in.", "司机：好，请上车。"],
    ["Me: Actually, could you drop me at the east gate?", "我：对了，能把我放在东门吗？"],
    ["Driver: No problem. East gate it is.", "司机：没问题，就到东门。"],
    ["Me: Great, thanks. How long will it take?", "我：太好了，谢谢。大概要多久？"],
    ["Driver: About twenty minutes. The roads are clear.", "司机：二十分钟左右，路况还行。"],
    ["Me: Could you turn up the AC a little?", "我：能把空调调大一点吗？"],
    ["Driver: Of course. Comfortable?", "司机：当然。现在舒服吗？"],
    ["Me: Yes, thanks. This heat is crazy.", "我：舒服了，谢谢。这天热得离谱。"],
    ["Driver: Tell me about it. Summer came early this year.", "司机：可不是嘛，今年夏天来得早。"],
    ["Me: We're here. Keep the change.", "我：到了，不用找零了。"],
    ["Driver: Thank you! Have a nice day!", "司机：谢谢！祝您愉快！"],
  ]},
  { id: 'outing-transit', cat: 'outing', emoji: '🚇', zh: '公交地铁', en: 'Bus & Subway', sents: [
    ["Me: Which line goes to City Library?", "我：去市图书馆坐几号线？"],
    ["Stranger: Line 3. This way, please.", "路人：3号线，这边请。"],
    ["Me: Thank you so much.", "我：太感谢了。"],
    ["Stranger: You're welcome. It's just two stops away.", "路人：不客气，就两站路。"],
    ["Me: Kids, hold the handrail, please.", "我：孩子们，抓好扶手。"],
    ["Emma: Mom, Leo is stepping on my shoes!", "Emma：妈妈，Leo 踩我鞋子！"],
    ["Me: Leo, stand still, okay?", "我：Leo，站好别动，好不好？"],
    ["Leo: Sorry, Emma.", "Leo：对不起，Emma。"],
    ["Me: Our stop is next. Get ready to get off.", "我：我们下一站下，准备下车了。"],
    ["Kids: Okay, Mom!", "孩子们：好的，妈妈！"],
    ["Me: Let's go, quick. Watch your step.", "我：快走，小心脚下。"],
    ["Emma: Made it! That was fast.", "Emma：下车啦！还挺快的。"],
  ]},
  { id: 'outing-checklist', cat: 'outing', emoji: '🎒', zh: '外出前检查', en: 'Before-Out Checklist', sents: [
    ["Me: Before we leave, let's check our stuff.", "我：出门前咱们检查下东西。"],
    ["Honey: Umbrellas? The forecast says rain.", "亲爱的：伞带了吗？预报说要下雨。"],
    ["Me: Check. Two umbrellas in my bag.", "我：带了，包里两把伞。"],
    ["Honey: IDs and cards?", "亲爱的：证件和卡呢？"],
    ["Me: Got them. Wallet, keys, phone... all here.", "我：都在。钱包、钥匙、手机……全齐了。"],
    ["Honey: Kids' water bottles?", "亲爱的：孩子们的水杯呢？"],
    ["Me: Emma has hers. Leo, where's your bottle?", "我：Emma 的拿了。Leo，你的水杯呢？"],
    ["Leo: It's in my backpack! See?", "Leo：在我书包里！你看！"],
    ["Me: Perfect. Alright, everything's ready.", "我：完美。好了，东西都齐了。"],
    ["Kids: Finally! Let's go!", "孩子们：终于好了！出发！"],
  ]},
  { id: 'outing-parking', cat: 'outing', emoji: '🅿️', zh: '停车', en: 'Finding Parking', sents: [
    ["Me: The parking lot is full. Let's drive around.", "我：停车场满了，咱们再绕一圈找找。"],
    ["Honey: There's a spot! Next to that blue car.", "亲爱的：那儿有个车位！就在那辆蓝车旁边。"],
    ["Me: Hmm, it's a tight squeeze.", "我：嗯，这个位置有点窄啊。"],
    ["Honey: You can do it. Go slow.", "亲爱的：你能停进去的，慢点来。"],
    ["Me: Okay... a little to the left... and stop!", "我：好……往左一点……停！"],
    ["Honey: Nice parking!", "亲爱的：停得漂亮！"],
    ["Me: That was stressful. Next time we come earlier.", "我：真费劲。下次咱们早点来。"],
    ["Honey: Agreed. Weekends are always packed.", "亲爱的：同意，周末总是爆满。"],
    ["Me: Let me take a photo of where we parked.", "我：我拍张照记下停在哪儿了。"],
    ["Honey: Smart move.", "亲爱的：明智之举。"],
  ]},

  /* ================= 购物消费 ================= */
  { id: 'shop-supermarket', cat: 'shopping', emoji: '🛒', zh: '超市采购', en: 'At the Supermarket', sents: [
    ["Me: Excuse me, where can I find milk?", "我：打扰一下，请问牛奶在哪儿？"],
    ["Clerk: It's in Aisle 3, next to the yogurt.", "店员：在3号货架，酸奶旁边。"],
    ["Me: Thanks. Do you have low-fat milk?", "我：谢谢。你们有低脂牛奶吗？"],
    ["Clerk: Yes, the blue boxes on the bottom shelf.", "店员：有的，底层货架蓝色盒装的。"],
    ["Me: Got it. How about eggs?", "我：找到了。鸡蛋在哪儿？"],
    ["Clerk: Aisle 4, on your right.", "店员：4号货架，在您右手边。"],
    ["Me: These eggs expire soon. Got fresher ones?", "我：这些鸡蛋快过期了，有更新鲜的吗？"],
    ["Clerk: Sure, this batch just came in today.", "店员：有的，这批是今天刚到的。"],
    ["Me: Perfect, I'll take these.", "我：太好了，我就拿这个。"],
    ["Clerk: Anything else I can help you with?", "店员：还需要别的吗？"],
    ["Me: No, that's all. Thank you!", "我：不用了，就这些，谢谢！"],
    ["Clerk: You're welcome. Have a nice day!", "店员：不客气，祝您愉快！"],
  ]},
  { id: 'shop-clothes', cat: 'shopping', emoji: '👕', zh: '服装店', en: 'Clothes Shopping', sents: [
    ["Me: Hi, I'm looking for a T-shirt, size M.", "我：你好，我想找一件 M 码的 T 恤。"],
    ["Clerk: Sure. What color do you like?", "店员：好的，您喜欢什么颜色？"],
    ["Me: White or gray, please.", "我：白色或者灰色吧。"],
    ["Clerk: Here you go. The fitting room is over there.", "店员：给您。试衣间在那边。"],
    ["Me: Thanks. Can I try this on?", "我：谢谢。我可以试穿吗？"],
    ["Clerk: Of course. Go ahead.", "店员：当然，请便。"],
    ["Me: It fits well. How much is it?", "我：挺合身的。多少钱？"],
    ["Clerk: It's 129. There's a sale today, twenty percent off.", "店员：129元，今天有促销，打八折。"],
    ["Me: Nice! If it doesn't fit, can I return it?", "我：不错！要是不合适能退吗？"],
    ["Clerk: Yes, within seven days, with the receipt.", "店员：可以，七天之内凭小票来退。"],
    ["Me: Great. I'll take it.", "我：好，我买了。"],
    ["Clerk: Thank you. This way to checkout, please.", "店员：谢谢，请这边结账。"],
  ]},
  { id: 'shop-convenience', cat: 'shopping', emoji: '🏪', zh: '便利店', en: 'At the Convenience Store', sents: [
    ["Me: Hi, do you sell phone chargers?", "我：你好，你们卖手机充电器吗？"],
    ["Clerk: Yes, by the counter. Type C or iPhone?", "店员：有的，就在收银台旁边。Type C 还是苹果的？"],
    ["Me: Type C, please. This one.", "我：Type C，就这个。"],
    ["Clerk: Anything else?", "店员：还要别的吗？"],
    ["Me: Two bottles of water and this sandwich.", "我：两瓶水，再加这个三明治。"],
    ["Clerk: Sure. That'll be thirty-five.", "店员：好，一共35元。"],
    ["Me: Can I pay with my phone?", "我：能手机支付吗？"],
    ["Clerk: Sure. Scan the code, please.", "店员：可以，请扫码。"],
    ["Me: Done. Thanks!", "我：付好了，谢谢！"],
    ["Clerk: Thank you! Have a good one!", "店员：谢谢！慢走！"],
  ]},
  { id: 'shop-fruits', cat: 'shopping', emoji: '🍎', zh: '选购水果', en: 'Buying Fruit', sents: [
    ["Me: Are these apples sweet or sour?", "我：这苹果是甜的还是酸的？"],
    ["Vendor: Sweet and crispy. Try a slice!", "摊主：又甜又脆，来尝一块！"],
    ["Me: Mmm, good. I'll take a bag.", "我：嗯，好吃。给我装一袋。"],
    ["Vendor: Sure. Anything else?", "摊主：好嘞。还要点啥？"],
    ["Me: Are the mangoes ripe? I want to eat them today.", "我：这芒果熟了吗？我今天就想吃。"],
    ["Vendor: These are ready today. Those ones need two more days.", "摊主：这批今天就能吃，那批还得放两天。"],
    ["Me: Then I'll take two ripe ones.", "我：那给我拿两个熟的吧。"],
    ["Vendor: Good choice. They're in season now.", "摊主：好眼光，现在正当季。"],
    ["Me: How much in total?", "我：一共多少钱？"],
    ["Vendor: Forty-two. I'll throw in an extra orange.", "摊主：42元，再送您一个橘子。"],
  ]},
  { id: 'shop-aftersale', cat: 'shopping', emoji: '🔁', zh: '售后沟通', en: 'Returns & Refunds', sents: [
    ["Me: Hi, I bought this kettle yesterday, but it doesn't work.", "我：你好，我昨天买的这个烧水壶，它不工作。"],
    ["Clerk: I'm sorry about that. Do you have the receipt?", "店员：很抱歉。您带小票了吗？"],
    ["Me: Yes, here it is.", "我：带了，给你。"],
    ["Clerk: Let me take a look. Hmm, it looks fine.", "店员：我看一下。嗯，外观没问题。"],
    ["Me: It just won't turn on. I tried different outlets.", "我：就是开不了机，我换了好几个插座都不行。"],
    ["Clerk: I see. It might be defective. Would you like a refund or an exchange?", "店员：明白了，可能是有质量问题。您想退款还是换一个？"],
    ["Me: I'd prefer a refund, please.", "我：我想退款。"],
    ["Clerk: No problem. Refunds go back to your original payment within three days.", "店员：没问题，退款三天内原路退回。"],
    ["Me: That works for me.", "我：可以。"],
    ["Clerk: Please sign here. And keep this slip.", "店员：请在这里签字，这张单据您收好。"],
    ["Me: Done. Thank you for your help.", "我：好了，谢谢你的帮助。"],
    ["Clerk: You're welcome. Sorry for the trouble!", "店员：不客气，给您添麻烦了！"],
  ]},

  /* ================= 亲子育儿 ================= */
  { id: 'par-schoolrun', cat: 'parenting', emoji: '🎒', zh: '孩子放学回家', en: 'After School', sents: [
    ["Me: Hi, sweethearts! How was school today?", "我：宝贝们回来啦！今天在学校怎么样？"],
    ["Emma: It was great! We had a science class.", "Emma：超棒！我们今天上了科学课。"],
    ["Me: Oh? What did you learn?", "我：哦？学到什么了？"],
    ["Emma: We did a fun experiment with magnets!", "Emma：我们做了磁铁实验，可好玩了！"],
    ["Me: That sounds fun! And you, Leo?", "我：听起来很有趣！Leo 你呢？"],
    ["Leo: I drew a dinosaur. It's super big!", "Leo：我画了一只恐龙，超级大！"],
    ["Me: Wow, show me later, okay?", "我：哇，一会儿给我看看，好吗？"],
    ["Leo: Okay! It's in my backpack.", "Leo：好！在我书包里。"],
    ["Me: Did you both finish your homework?", "我：你们的作业都写完了吗？"],
    ["Emma: Almost. I have one page left.", "Emma：快写完了，还剩一页。"],
    ["Me: Okay. Finish it before dinner.", "我：好，晚饭前写完哦。"],
    ["Kids: Okay, Mom!", "孩子们：好的，妈妈！"],
  ]},
  { id: 'par-homework', cat: 'parenting', emoji: '📖', zh: '辅导学习', en: 'Homework Time', sents: [
    ["Me: Emma, is your homework done?", "我：Emma，作业写完了吗？"],
    ["Emma: Math is done. English is hard.", "Emma：数学写完了，英语有点难。"],
    ["Me: What's the problem? Let me see.", "我：哪里不会？给我看看。"],
    ["Emma: These words. I don't know how to spell them.", "Emma：这些单词，我不会拼。"],
    ["Me: Okay, let's read them together. \"Wednesday.\"", "我：好，咱们一起读。“Wednesday”。"],
    ["Emma: Wednesday. W-E-D-N-E-S-D-A-Y.", "Emma：Wednesday。W-E-D-N-E-S-D-A-Y。"],
    ["Me: Perfect! Now \"library.\"", "我：完美！再来“library”。"],
    ["Emma: Library. L-I-B-R-A-R-Y. Got it!", "Emma：Library。L-I-B-R-A-R-Y。记住了！"],
    ["Me: Great job! Let's read this little story too.", "我：真棒！咱们再把这个小故事读一遍吧。"],
    ["Emma: Okay! \"The cat is on the mat...\"", "Emma：好！“The cat is on the mat...”"],
    ["Me: Excellent reading! You're getting so good at this.", "我：读得真好！你越来越厉害了。"],
    ["Emma: Thanks, Mom! English is fun now.", "Emma：谢谢妈妈！现在我爱上英语了。"],
  ]},
  { id: 'par-play', cat: 'parenting', emoji: '🧸', zh: '居家玩耍', en: 'Playtime at Home', sents: [
    ["Leo: Mom! Look at my tower! It's so tall!", "Leo：妈妈！你看我搭的塔！好高呀！"],
    ["Me: Wow, amazing! How did you do that?", "我：哇，太厉害了！你怎么搭的呀？"],
    ["Leo: I stacked them one by one!", "Leo：我一块一块叠起来的！"],
    ["Me: Careful, don't stand on the couch, please.", "我：小心点，别站在沙发上哦。"],
    ["Leo: Okay... Oops!", "Leo：好……哎呀！"],
    ["Me: It's okay. Let's pick the blocks up together.", "我：没事没事，咱们一起把积木捡起来。"],
    ["Emma: Mom, can you play cards with us?", "Emma：妈妈，你能跟我们打牌吗？"],
    ["Me: Sure! What game?", "我：当然！玩什么？"],
    ["Emma: Old Maid! Leo loves it.", "Emma：抽乌龟！Leo 最爱玩了。"],
    ["Leo: Yeah! Let's play!", "Leo：耶！快开始吧！"],
    ["Me: Alright, but no cheating this time, Leo.", "我：好，不过 Leo 这次不许耍赖哦。"],
    ["Leo: I never cheat!", "Leo：我从来不耍赖！"],
  ]},
  { id: 'par-park', cat: 'parenting', emoji: '🛝', zh: '公园遛娃', en: 'At the Playground', sents: [
    ["Emma: Mom, can I go on the slide?", "Emma：妈妈，我能去玩滑梯吗？"],
    ["Me: Sure, but wait your turn, okay?", "我：可以，但要排队等轮到你，好吗？"],
    ["Emma: Okay!", "Emma：好！"],
    ["Leo: Mom, push me on the swing! Higher!", "Leo：妈妈，推我荡秋千！再高一点！"],
    ["Me: Hold on tight! Not too high, Leo.", "我：抓牢啦！Leo，别荡太高。"],
    ["Leo: Whee! This is fun!", "Leo：哇！太好玩了！"],
    ["Me: Emma, come down from there. It's too high!", "我：Emma，从那上面下来，太高了！"],
    ["Emma: Sorry, Mom. It looked fun.", "Emma：对不起妈妈，我觉得好玩就爬上去了。"],
    ["Me: I know, but safety first, remember?", "我：妈妈知道，但是安全第一，记得吗？"],
    ["Emma: I remember. I'll stay lower.", "Emma：记得，我会小心的。"],
    ["Me: Good. Ten more minutes, then we go home.", "我：乖。再玩十分钟，然后咱们回家。"],
    ["Kids: Aww, okay...", "孩子们：哎呀，好吧……"],
  ]},
  { id: 'par-comfort', cat: 'parenting', emoji: '💗', zh: '安抚情绪', en: 'Comforting the Kids', sents: [
    ["Leo: Mom! Emma broke my toy car!", "Leo：妈妈！Emma 把我的玩具车弄坏了！"],
    ["Me: Oh no. Come here, buddy. Let me see.", "我：哎呀，过来宝贝，我看看。"],
    ["Leo: It's my favorite one...", "Leo：这是我最喜欢的一辆……"],
    ["Me: I know, I know. It hurts to lose a favorite toy.", "我：妈妈知道，妈妈知道，弄坏心爱的玩具是挺难受的。"],
    ["Leo: I want it fixed!", "Leo：我想要它修好！"],
    ["Me: We'll try to fix it together. If not, we'll find a new one.", "我：咱们一起试着修。修不好的话，就再给你找一辆新的。"],
    ["Leo: Really?", "Leo：真的吗？"],
    ["Me: Really. Now, take a deep breath. Feel better?", "我：真的。来，深呼吸一下，好点了吗？"],
    ["Leo: A little bit...", "Leo：好点了……"],
    ["Me: Emma wants to say sorry. Can you two give each other a hug?", "我：Emma 想跟你说对不起。你们俩能抱抱和好吗？"],
    ["Emma: Sorry, Leo. I didn't mean to.", "Emma：对不起 Leo，我不是故意的。"],
    ["Leo: Okay. I forgive you.", "Leo：好吧，我原谅你了。"],
  ]},
  { id: 'par-tutorprep', cat: 'parenting', emoji: '🖥️', zh: '外教课前', en: 'Before the English Class', sents: [
    ["Me: Emma, your English class starts in ten minutes.", "我：Emma，你的英语课还有十分钟就开始了。"],
    ["Emma: Okay, Mom. Where's my tablet?", "Emma：好的妈妈。我的平板呢？"],
    ["Me: On the table, charged and ready.", "我：在桌上，充好电了。"],
    ["Emma: Great. Is my homework done? Let me check.", "Emma：太好了。作业写完了吗？我检查一下。"],
    ["Me: You finished it. Want to warm up with a quick word game?", "我：写完了。要不要先玩个单词小游戏热热身？"],
    ["Emma: Yes! Word chain!", "Emma：要！词语接龙！"],
    ["Me: Okay! \"Apple.\"", "我：好！“Apple。”"],
    ["Emma: \"Egg!\" Now your turn!", "Emma：“Egg！”该你啦！"],
    ["Me: \"Garden.\" Good job. Okay, class time!", "我：“Garden。”真棒。好啦，上课啦！"],
    ["Emma: Wish me luck!", "Emma：祝我好运！"],
  ]},
  { id: 'par-bedtime', cat: 'parenting', emoji: '🌙', zh: '睡前亲子时光', en: 'Bedtime Stories', sents: [
    ["Me: Alright, time to get ready for bed.", "我：好啦，该准备睡觉啦。"],
    ["Kids: Aww, not yet!", "孩子们：哎呀，还早呢！"],
    ["Me: Just one story tonight. Pick one.", "我：今晚只讲一个故事，选一本吧。"],
    ["Leo: This one! About the little bear!", "Leo：这本！讲小熊的！"],
    ["Me: Good choice. Get cozy. \"Once upon a time, a little bear...\"", "我：选得好。躺舒服。“从前呀，有一只小熊……”"],
    ["Kids: ...", "孩子们：（听得入神）"],
    ["Me: \"...and the bear finally found his way home.\" The end.", "我：“……小熊终于回到了家。”讲完啦。"],
    ["Leo: Again! Again!", "Leo：再讲一遍！再讲一遍！"],
    ["Me: Tomorrow night, Leo. Now, goodnight kisses.", "我：明天晚上再讲哦。来，晚安亲亲。"],
    ["Kids: Goodnight, Mom!", "孩子们：妈妈晚安！"],
    ["Me: Goodnight, my babies. Sweet dreams.", "我：晚安，我的宝贝们，做个好梦。"],
    ["Emma: Love you, Mom!", "Emma：爱你妈妈！"],
  ]},

  /* ================= 运动健身 ================= */
  { id: 'fit-gym', cat: 'fitness', emoji: '🏋️', zh: '健身训练', en: 'At the Gym', sents: [
    ["Friend: Hey! Are you training chest today?", "朋友：嘿！你今天练胸吗？"],
    ["Me: Yeah, bench press first. Want to spot me?", "我：对，先练卧推。帮我保护一下？"],
    ["Friend: Sure. How many sets are you doing?", "朋友：没问题。你打算做几组？"],
    ["Me: Four sets of ten. Let's start light.", "我：四组，每组十个。先从小重量开始。"],
    ["Friend: Nice form. You can add more weight.", "朋友：姿势很标准，可以加重量了。"],
    ["Me: Maybe next set. Don't want to push too hard.", "我：下一组吧，不想一下太猛。"],
    ["Friend: Smart. Rest for a minute. Drink some water.", "朋友：明智。休息一分钟，喝点水。"],
    ["Me: Thanks. Your turn after this set.", "我：谢了。这组完了换你。"],
    ["Friend: Deal. Should we do some pushups too?", "朋友：一言为定。要不要再来点俯卧撑？"],
    ["Me: Sure, three sets. I can handle that.", "我：行，来三组，我还扛得住。"],
    ["Friend: Great workout today!", "朋友：今天练得真爽！"],
    ["Me: Same. See you tomorrow?", "我：你也是。明天还来吗？"],
  ]},
  { id: 'fit-home', cat: 'fitness', emoji: '💪', zh: '居家力量训练', en: 'Home Workout', sents: [
    ["Me: Honey, let's do a quick workout together.", "我：亲爱的，咱们一起快速锻炼一下吧。"],
    ["Honey: Okay, what are we doing?", "亲爱的：好啊，练什么？"],
    ["Me: Some squats and planks. Just fifteen minutes.", "我：深蹲和平板支撑，就十五分钟。"],
    ["Honey: Fifteen minutes? You said that yesterday too.", "亲爱的：十五分钟？你昨天也是这么说的。"],
    ["Me: I mean it this time! Squats first. Ready?", "我：这次是真的！先来深蹲，准备好了吗？"],
    ["Honey: Ready. One, two, three...", "亲爱的：好了。一、二、三……"],
    ["Me: Good! Now the plank. Hold it for thirty seconds.", "我：很好！现在平板支撑，坚持三十秒。"],
    ["Honey: My arms are shaking already...", "亲爱的：我的手臂已经开始抖了……"],
    ["Me: Ten more seconds! You can do it!", "我：再坚持十秒！你能行！"],
    ["Honey: Done! That's enough for today.", "亲爱的：完成！今天的量够了。"],
  ]},
  { id: 'fit-jog', cat: 'fitness', emoji: '🏃', zh: '慢跑散步', en: 'Jogging & Walking', sents: [
    ["Friend: Nice evening for a jog, right?", "朋友：今晚很适合跑步，是吧？"],
    ["Me: Totally. The air feels so fresh.", "我：可不是嘛，空气特别清新。"],
    ["Friend: How far are we going today?", "朋友：今天跑多远？"],
    ["Me: Let's do three kilometers. Easy pace.", "我：跑三公里吧，慢点跑。"],
    ["Friend: Sounds good. I've been sitting all day.", "朋友：行。我坐了一整天了。"],
    ["Me: Me too. This feels great.", "我：我也是，跑起来真舒服。"],
    ["Friend: Look at that sunset. Gorgeous.", "朋友：你看那夕阳，太美了。"],
    ["Me: Yeah. Let's walk for a bit and enjoy it.", "我：是啊。咱们走一会儿，欣赏欣赏。"],
    ["Friend: Good idea. Same time tomorrow?", "朋友：好主意。明天同一时间？"],
    ["Me: You bet.", "我：必须的。"],
  ]},

  /* ================= 健康就医 ================= */
  { id: 'health-tell', cat: 'health', emoji: '🗣️', zh: '身体不适', en: 'Feeling Unwell', sents: [
    ["Me: Honey, I don't feel so good today.", "我：亲爱的，我今天不太舒服。"],
    ["Honey: What's wrong? You look pale.", "亲爱的：怎么了？你脸色不太好。"],
    ["Me: My head hurts, and I feel dizzy.", "我：头疼，还有点晕。"],
    ["Honey: Did you sleep well last night?", "亲爱的：昨晚没睡好吗？"],
    ["Me: Not really. I kept waking up.", "我：睡得不好，老醒。"],
    ["Honey: Maybe you're coming down with something.", "亲爱的：可能要感冒了。"],
    ["Me: Yeah. And my throat is a little sore.", "我：嗯，嗓子也有点疼。"],
    ["Honey: I'll make you some hot tea. Go rest.", "亲爱的：我给你泡杯热茶，快去休息。"],
    ["Me: Thanks. I'll lie down for a while.", "我：谢谢，我去躺一会儿。"],
    ["Honey: If it gets worse, we'll see a doctor.", "亲爱的：要是严重了，咱们就去医院。"],
  ]},
  { id: 'health-pharmacy', cat: 'health', emoji: '💊', zh: '药店购药', en: 'At the Pharmacy', sents: [
    ["Me: Hi, I've got a sore throat and a bit of a fever.", "我：你好，我嗓子疼，还有点发烧。"],
    ["Pharmacist: I see. How high is the fever?", "药剂师：明白，烧到多少度？"],
    ["Me: Around 37.8, since last night.", "我：大概37度8，从昨晚开始的。"],
    ["Pharmacist: Any other symptoms? Cough or runny nose?", "药剂师：还有别的症状吗？咳嗽或流鼻涕？"],
    ["Me: Just a light cough. Nothing else.", "我：有点轻微咳嗽，别的没有。"],
    ["Pharmacist: Okay. This syrup will help the cough and throat.", "药剂师：好的。这个糖浆能缓解咳嗽和嗓子疼。"],
    ["Me: How often should I take it?", "我：一天吃几次？"],
    ["Pharmacist: Three times a day, after meals.", "药剂师：一天三次，饭后服用。"],
    ["Me: Anything else I should know?", "我：还有什么要注意的吗？"],
    ["Pharmacist: Drink plenty of water and get some rest. If the fever lasts more than two days, see a doctor.", "药剂师：多喝水多休息。要是烧两天不退，就去看医生。"],
    ["Me: Got it. Thanks for your help!", "我：明白了，谢谢！"],
    ["Pharmacist: You're welcome. Get well soon!", "药剂师：不客气，早日康复！"],
  ]},
  { id: 'health-doctor', cat: 'health', emoji: '🏥', zh: '门诊问诊', en: 'At the Clinic', sents: [
    ["Doctor: Good morning. What's bothering you today?", "医生：早上好，今天哪里不舒服？"],
    ["Me: Hi, Doctor. I've had a headache and a fever since yesterday.", "我：医生你好，我从昨天开始头疼发烧。"],
    ["Doctor: How high is your temperature?", "医生：体温多少？"],
    ["Me: About 38 degrees last night.", "我：昨晚量了大概38度。"],
    ["Doctor: Any cough, sore throat, or runny nose?", "医生：咳嗽、嗓子疼或者流鼻涕吗？"],
    ["Me: A little sore throat. No runny nose.", "我：嗓子有点疼，不流鼻涕。"],
    ["Doctor: Let me check your throat. Open wide and say \"ah.\"", "医生：我看看你的嗓子。张大嘴说“啊”。"],
    ["Me: Ahh...", "我：啊……"],
    ["Doctor: It's a bit red. Looks like a common cold. I'll give you some medicine.", "医生：有点红，看起来是普通感冒。我给你开点药。"],
    ["Me: Okay. Do I need to take any tests?", "我：好的。需要做什么检查吗？"],
    ["Doctor: Not necessary for now. Rest well and drink lots of water.", "医生：暂时不用。好好休息，多喝水。"],
    ["Me: Thank you, Doctor.", "我：谢谢医生。"],
  ]},
  { id: 'health-checkup', cat: 'health', emoji: '📋', zh: '预约体检', en: 'Booking a Checkup', sents: [
    ["Me: Hello, I'd like to book a health checkup.", "我：你好，我想预约一次体检。"],
    ["Staff: Sure. We have several packages. Which one do you prefer?", "工作人员：好的，我们有几种套餐，您想选哪种？"],
    ["Me: What's the difference between the basic and the standard package?", "我：基础套餐和标准套餐有什么区别？"],
    ["Staff: The standard one adds heart and stomach checks.", "工作人员：标准套餐多了心脏和胃的检查。"],
    ["Me: I see. I'll take the standard one.", "我：明白了。我要标准套餐。"],
    ["Staff: Great. Which day works for you?", "工作人员：好的。您哪天方便？"],
    ["Me: How about next Saturday morning?", "我：下周六上午怎么样？"],
    ["Staff: Let me check... Yes, we have an opening at 9 a.m.", "工作人员：我看一下……有的，上午九点有位。"],
    ["Me: Perfect. Please book it for me.", "我：太好了，就帮我约这个吧。"],
    ["Staff: Done. Remember not to eat breakfast that morning.", "工作人员：约好了。当天早上记得不要吃早饭。"],
  ]},

  /* ================= 办事业务 ================= */
  { id: 'err-bank', cat: 'errands', emoji: '🏦', zh: '银行业务', en: 'At the Bank', sents: [
    ["Me: Hi, I'd like to ask about fixed deposits.", "我：你好，我想咨询一下定期存款。"],
    ["Clerk: Of course. We have three-month, one-year, and three-year terms.", "柜员：当然可以。我们有三个月、一年和三年期的。"],
    ["Me: What's the interest rate for the one-year term?", "我：一年期的利率是多少？"],
    ["Clerk: Currently two point one five percent.", "柜员：目前是百分之二点一五。"],
    ["Me: And is there a minimum amount?", "我：有最低存款金额吗？"],
    ["Clerk: Fifty thousand for the higher rate.", "柜员：要享受这个利率，最低五万元。"],
    ["Me: I see. If I need the money early, can I withdraw it?", "我：明白。如果我提前要用钱，能取出来吗？"],
    ["Clerk: Yes, but the interest will be calculated at the current rate instead.", "柜员：可以，但利息会按活期利率来算。"],
    ["Me: Got it. I'd like to open a one-year deposit.", "我：明白了。我想办一笔一年期定期。"],
    ["Clerk: Sure. Please fill out this form.", "柜员：好的，请填一下这张表。"],
  ]},
  { id: 'err-parcelshop', cat: 'errands', emoji: '📮', zh: '快递驿站', en: 'Parcel Pickup', sents: [
    ["Me: Hi, I'm here to pick up a package.", "我：你好，我来取个快递。"],
    ["Clerk: Sure. Pickup code, please?", "店员：好的，请出示取件码。"],
    ["Me: It's 8-3-5021.", "我：8-3-5021。"],
    ["Clerk: Let me check... Here it is. One package, right?", "店员：我查一下……找到了。就一件，对吧？"],
    ["Me: Actually, I should have two. The other one came yesterday.", "我：不对呀，我应该有两件，另一件昨天就到了。"],
    ["Clerk: Hmm, let me look again. Sorry, here it is. Missed it earlier.", "店员：嗯，我再看看。抱歉，在这儿呢，刚才漏了。"],
    ["Me: No problem. By the way, a friend's package was sent here by mistake last week.", "我：没事。对了，上周有个朋友的包裹错送到你们这儿了。"],
    ["Clerk: Oh? Do you have the tracking number?", "店员：哦？有运单号吗？"],
    ["Me: Yes, I'll send it to you.", "我：有，我发给你。"],
    ["Clerk: Great. We'll look into it and call you back.", "店员：好的，我们查一下再给您回电。"],
  ]},
  { id: 'err-property', cat: 'errands', emoji: '🏘️', zh: '对接物业', en: 'Calling Property Management', sents: [
    ["Me: Hi, I'm calling from Building 6, Unit 2.", "我：你好，我是6栋2单元的住户。"],
    ["Agent: Yes, how can I help you?", "物业：好的，请问有什么事？"],
    ["Me: The kitchen faucet is leaking badly.", "我：我家厨房水龙头漏水漏得厉害。"],
    ["Agent: I'm sorry to hear that. Is it dripping or spraying?", "物业：很抱歉。是滴水还是喷涌？"],
    ["Me: Dripping, but it won't stop.", "我：是一滴一滴的，但一直不停。"],
    ["Agent: Got it. I'll send a repairman this afternoon.", "物业：明白了，今天下午派师傅过去。"],
    ["Me: Also, when is the management fee due this quarter?", "我：对了，这季度的物业费什么时候交？"],
    ["Agent: It's due by the end of this month.", "物业：这个月底前交就行。"],
    ["Me: Okay. Can I pay it online?", "我：好的，能在网上交吗？"],
    ["Agent: Yes, through our app or the mini program.", "物业：可以，用我们的 App 或小程序都行。"],
  ]},

  /* ================= 社交聚会 ================= */
  { id: 'soc-invite', cat: 'social', emoji: '🤝', zh: '和朋友相约', en: 'Making Plans', sents: [
    ["Friend: Hey! Are you free this Saturday?", "朋友：嘿！这周六有空吗？"],
    ["Me: Saturday? Let me think... Yeah, I'm free.", "我：周六？我想想……有空。"],
    ["Friend: Let's grab lunch together. It's been ages!", "朋友：一起吃个午饭吧，好久不见了！"],
    ["Me: Great idea! Where should we go?", "我：好主意！去哪儿吃？"],
    ["Friend: How about that new place near the park?", "朋友：公园附近那家新开的店怎么样？"],
    ["Me: The hot pot place? Sounds good. What time?", "我：火锅店吗？不错。几点？"],
    ["Friend: Eleven thirty? We can beat the lunch rush.", "朋友：十一点半？能避开吃饭高峰。"],
    ["Me: Perfect. Eleven thirty works for me.", "我：完美，十一点半可以。"],
    ["Friend: Should we invite Lily too?", "朋友：要不要也叫上 Lily？"],
    ["Me: Sure! The more, the merrier.", "我：当然！人多热闹。"],
    ["Friend: Great. I'll set it up in our group chat.", "朋友：好，我在群里约一下。"],
    ["Me: Awesome. See you Saturday!", "我：太好了，周六见！"],
  ]},
  { id: 'soc-guests', cat: 'social', emoji: '🛋️', zh: '家里接待客人', en: 'Having Guests Over', sents: [
    ["Me: Hi, Lily! Welcome! Come on in.", "我：Lily 你好！欢迎欢迎，快请进。"],
    ["Lily: Hi! Thanks for having me. Your home is lovely!", "Lily：你好！谢谢邀请，你家真漂亮！"],
    ["Me: Thanks! Make yourself at home. Can I get you some tea?", "我：谢谢！别客气，就当自己家。给你倒杯茶？"],
    ["Lily: Yes, please. Green tea if you have it.", "Lily：好啊，有绿茶的话就来绿茶。"],
    ["Me: Sure. And try these cookies. I baked them this morning.", "我：没问题。尝尝这些饼干，我今天早上刚烤的。"],
    ["Lily: Oh wow, they're delicious!", "Lily：哇，太好吃了！"],
    ["Me: Glad you like them. How's everything at work?", "我：喜欢就好。你工作最近怎么样？"],
    ["Lily: Busy, but good. We just finished a big project.", "Lily：挺忙的，不过还不错。我们刚做完一个大项目。"],
    ["Me: That's great. You should tell me all about it.", "我：那太好了。快跟我好好讲讲。"],
    ["Lily: I will! But first, where's your bathroom?", "Lily：一定的！不过先告诉我洗手间在哪儿？"],
    ["Me: Down the hall, on your right.", "我：沿着走廊走，右手边就是。"],
    ["Lily: Thanks!", "Lily：谢谢！"],
  ]},
  { id: 'soc-restaurant', cat: 'social', emoji: '🍽️', zh: '餐厅就餐', en: 'Dining Out', sents: [
    ["Me: Hi, a table for three, please.", "我：你好，我们要一张三人桌。"],
    ["Host: Sure. This way, please. Here are your menus.", "服务员：好的，这边请。这是菜单。"],
    ["Me: Thanks. What do you recommend?", "我：谢谢。有什么推荐的吗？"],
    ["Host: The grilled fish is very popular.", "服务员：烤鱼很受欢迎。"],
    ["Me: Sounds good. We'll take the grilled fish and Kung Pao chicken.", "我：听起来不错。我们要烤鱼和宫保鸡丁。"],
    ["Host: Anything else?", "服务员：还要别的吗？"],
    ["Me: One tomato egg soup, please. That's all.", "我：再来一份西红柿鸡蛋汤。就这些。"],
    ["Host: Got it. It'll be about fifteen minutes.", "服务员：好的，大概十五分钟上菜。"],
    ["Me: Could we get some more water, please?", "我：能再给我们加点水吗？"],
    ["Host: Of course. Right away.", "服务员：当然，马上来。"],
    ["Me: Check, please. Can I pay by phone?", "我：买单。能手机支付吗？"],
    ["Host: Sure. Just scan here. Thank you!", "服务员：可以，扫这里就行。谢谢！"],
  ]},
  { id: 'soc-catchup', cat: 'social', emoji: '☕', zh: '和好友叙旧', en: 'Catching Up with a Friend', sents: [
    ["Me: Lily! It's so good to see you!", "我：Lily！见到你真高兴！"],
    ["Lily: You too! Wow, it really has been ages.", "Lily：我也是！哇，真的好久没见了。"],
    ["Me: Right? How have you been?", "我：可不是嘛。你最近怎么样？"],
    ["Lily: Pretty good. Busy with the kids, you know how it is.", "Lily：挺好的，就是忙孩子，你也懂的。"],
    ["Me: I do! Two kids keep me on my toes all day.", "我：太懂了！俩孩子让我一天从早忙到晚。"],
    ["Lily: Same here. How are Emma and Leo doing?", "Lily：我也是。Emma 和 Leo 还好吗？"],
    ["Me: They're great. Emma started swim class. Leo loves drawing.", "我：他们都很好。Emma 开始上游泳课了，Leo 迷上了画画。"],
    ["Lily: That's so sweet. Kids grow up so fast.", "Lily：真可爱。孩子们长得太快了。"],
    ["Me: They really do. And how's your job going?", "我：是啊。你工作呢，还顺利吗？"],
    ["Lily: Not bad. Thinking about a change, actually.", "Lily：还行吧。其实我在考虑换工作。"],
    ["Me: Oh really? Tell me more.", "我：哦真的吗？快跟我详细说说。"],
    ["Lily: Well...", "Lily：是这样的……"],
  ]},

  /* ================= 休闲娱乐 ================= */
  { id: 'lei-drama', cat: 'leisure', emoji: '📺', zh: '追剧观影', en: 'Talking About TV Shows', sents: [
    ["Me: Have you seen the new episode yet?", "我：新的一集你看了吗？"],
    ["Honey: Yes! It was so good. I won't spoil it.", "亲爱的：看了！太精彩了，我就不剧透了。"],
    ["Me: Come on, just a tiny hint!", "我：拜托，就给一点点提示嘛！"],
    ["Honey: Nope. You'll love the ending though.", "亲爱的：不行。不过结局你肯定喜欢。"],
    ["Me: Now I'm really curious. Let's watch it together tonight.", "我：这下我更好奇了。今晚咱们一起看吧。"],
    ["Honey: Deal. I'll make popcorn.", "亲爱的：一言为定，我来爆爆米花。"],
    ["Me: Perfect. Oh, and Season 2 starts next month!", "我：完美。对了，第二季下个月开播！"],
    ["Honey: I know! I can hardly wait.", "亲爱的：我知道！等不及了。"],
    ["Me: Same. This show gets better every season.", "我：我也是。这剧一季比一季好看。"],
    ["Honey: Best show we've watched all year.", "亲爱的：这是咱们今年看过最好的剧。"],
  ]},
  { id: 'lei-weekend', cat: 'leisure', emoji: '🗓️', zh: '规划周末', en: 'Planning the Weekend', sents: [
    ["Me: Any plans for the weekend?", "我：周末有什么安排吗？"],
    ["Honey: Not yet. What do you have in mind?", "亲爱的：还没有呢。你有什么想法？"],
    ["Me: The weather looks nice. How about a picnic in the park?", "我：天气看起来不错，去公园野餐怎么样？"],
    ["Honey: Nice idea. We could bring a kite for the kids.", "亲爱的：好主意，咱们可以给孩子带个风筝。"],
    ["Me: They'd love that. Or we could visit the new aquarium.", "我：他们肯定喜欢。或者咱们去新开的海洋馆？"],
    ["Honey: Oh, the aquarium sounds fun! Leo loves fish.", "亲爱的：哇，海洋馆不错！Leo 最喜欢鱼了。"],
    ["Me: True. Let's ask the kids which one they prefer.", "我：也是。问问孩子们想去哪个吧。"],
    ["Honey: Kids! Park or aquarium?", "亲爱的：孩子们！去公园还是海洋馆？"],
    ["Emma: Aquarium!", "Emma：海洋馆！"],
    ["Leo: Park! I want to fly the kite!", "Leo：公园！我要放风筝！"],
    ["Me: Haha, split vote. Aquarium on Saturday, park on Sunday.", "我：哈哈，意见不一。那这样吧，周六海洋馆，周日公园。"],
    ["Honey: Perfect. Best of both worlds.", "亲爱的：完美，两全其美。"],
  ]},
  { id: 'lei-park', cat: 'leisure', emoji: '🌳', zh: '逛公园', en: 'A Walk in the Park', sents: [
    ["Me: What a beautiful day!", "我：今天天气真好！"],
    ["Honey: Perfect for a walk. Look at all the flowers!", "亲爱的：太适合散步了。你看这些花！"],
    ["Me: Gorgeous. Spring is my favorite season.", "我：真美。春天是我最喜欢的季节。"],
    ["Honey: Mine too. Hey, let's rent a paddle boat!", "亲爱的：我也是。哎，咱们去租条脚踏船吧！"],
    ["Me: On the lake? That sounds fun.", "我：湖上吗？听着挺有意思。"],
    ["Honey: The kids will love it. Let's go!", "亲爱的：孩子们肯定喜欢。走吧！"],
    ["Me: Okay, but life jackets first. Safety first, remember?", "我：行，不过先穿救生衣。安全第一，记得吗？"],
    ["Honey: Absolutely. Come on, kids!", "亲爱的：那当然。来吧孩子们！"],
    ["Me: Look at them paddling. They're having a blast.", "我：看他们踩得多开心，玩得真尽兴。"],
    ["Honey: Best weekend in a while.", "亲爱的：这是最近最开心的周末了。"],
  ]},

  /* ================= 职场办公 ================= */
  { id: 'work-desk', cat: 'work', emoji: '🖥️', zh: '沟通需求与进度', en: 'Design Requests & Progress', sents: [
    ["Colleague: Hey, got a minute? About the new homepage design.", "同事：嘿，有空吗？想聊聊首页的新设计。"],
    ["Me: Sure. What's up?", "我：当然，怎么了？"],
    ["Colleague: The client wants the banner changed. Again.", "同事：客户又想改 banner 了。又来。"],
    ["Me: Again? What do they want this time?", "我：又改？这次想要什么？"],
    ["Colleague: Bigger logo, brighter colors.", "同事：更大的 logo，更亮的颜色。"],
    ["Me: Hmm, that might hurt the layout. Let me think of a better way.", "我：嗯，那样可能会破坏版式。我想想有没有更好的方案。"],
    ["Colleague: Okay. How's the icon set coming along?", "同事：好。那套图标画得怎么样了？"],
    ["Me: Almost done. I'll send it over by Friday.", "我：快完成了，周五前发你。"],
    ["Colleague: Great. And the prototype?", "同事：太好了。那原型呢？"],
    ["Me: Still working on the user flow. Should be ready Monday.", "我：流程图还在做，周一应该能好。"],
    ["Colleague: Sounds good. Let me know if you need anything.", "同事：行。有需要帮忙的随时说。"],
    ["Me: Will do. Thanks!", "我：一定的，谢谢！"],
  ]},
  { id: 'work-meeting', cat: 'work', emoji: '📊', zh: '会议沟通', en: 'In a Meeting', sents: [
    ["Manager: Okay, let's start. First, the design review.", "经理：好，我们开始吧。先讲设计评审。"],
    ["Me: Sure. Let me share my screen.", "我：好，我共享一下屏幕。"],
    ["Manager: Go ahead.", "经理：开始吧。"],
    ["Me: Here's the new checkout flow. We simplified the steps from five to three.", "我：这是新的结账流程，我们把步骤从五步简化到了三步。"],
    ["Manager: Nice. Any feedback, everyone?", "经理：不错。大家有什么意见？"],
    ["Colleague: Looks clean. Just one question about the button colors.", "同事：看着挺干净。就问一下按钮的颜色。"],
    ["Me: Good catch. I'll adjust the contrast for better readability.", "我：问得好。我会调高对比度，让可读性更好。"],
    ["Colleague: Thanks. That works.", "同事：谢谢，这样就挺好。"],
    ["Manager: Great. What's the timeline for the final version?", "经理：很好。最终版大概什么时候出？"],
    ["Me: We'll finish the visuals by Thursday, and the full prototype next Tuesday.", "我：视觉稿周四完成，完整原型下周二。"],
    ["Manager: Perfect. Let's aim for that. Moving on.", "经理：很好，就这么定。下一个议题。"],
    ["Colleague: Great. Let's talk after the meeting.", "同事：好，会后再细聊。"],
  ]},
  { id: 'work-chitchat', cat: 'work', emoji: '☕', zh: '办公室闲聊', en: 'Office Small Talk', sents: [
    ["Colleague: Coffee break?", "同事：休息一下，来杯咖啡？"],
    ["Me: Yes, I need it. I stayed up late last night.", "我：必须来一杯。我昨晚熬夜了。"],
    ["Colleague: Working late again? Don't burn yourself out.", "同事：又加班？别把自己累垮了。"],
    ["Me: Just finalizing the design draft. You know how it is.", "我：就是在赶设计稿嘛，你懂的。"],
    ["Colleague: I do. By the way, great job on the presentation yesterday.", "同事：懂。对了，你昨天的汇报做得真好。"],
    ["Me: Thanks! I was pretty nervous, honestly.", "我：谢谢！说实话我还挺紧张的。"],
    ["Colleague: Really? Couldn't tell at all. You looked confident.", "同事：真的吗？完全看不出来，你显得很自信。"],
    ["Me: Haha, glad to hear that.", "我：哈哈，听你这么说我就放心了。"],
    ["Colleague: So, lunch together today?", "同事：对了，今天一起吃午饭？"],
    ["Me: Sure. The usual place?", "我：好啊，老地方？"],
  ]},

  /* ================= 短途出游 ================= */
  { id: 'trip-pack', cat: 'trip', emoji: '🎒', zh: '出游筹备', en: 'Packing for a Trip', sents: [
    ["Me: Okay, let's pack for the trip. Two days, one night.", "我：好，咱们收拾行李。两天一晚。"],
    ["Honey: Right. The kids need two outfits each.", "亲爱的：嗯。孩子们每人带两套衣服。"],
    ["Me: Check. Pajamas and extra socks too.", "我：好。还有睡衣和备用袜子。"],
    ["Honey: Don't forget the chargers. Phone and tablet.", "亲爱的：别忘了充电器，手机和平板的。"],
    ["Me: Got them. Where's the sunscreen?", "我：拿了。防晒霜在哪儿？"],
    ["Honey: In the bathroom cabinet. I'll grab it.", "亲爱的：在洗手间柜子里，我去拿。"],
    ["Me: Thanks. Kids, pack your own toys. Just two each!", "我：谢谢。孩子们，自己的玩具自己装，每人只许带两个！"],
    ["Kids: Just two? Aww...", "孩子们：才两个？哎呀……"],
    ["Me: Two. You have to carry your own bags.", "我：就两个。你们得自己背包。"],
    ["Emma: Fine... Leo, help me zip this up!", "Emma：好吧……Leo，帮我拉一下拉链！"],
    ["Me: Everything's in. Doors locked, windows closed.", "我：东西都齐了。门锁好，窗户关好了。"],
    ["Honey: Ready! Let's hit the road.", "亲爱的：准备完毕！出发吧。"],
  ]},
  { id: 'trip-ask', cat: 'trip', emoji: '🗺️', zh: '外出问路', en: 'Asking for Directions', sents: [
    ["Me: Excuse me, how do I get to the old town?", "我：打扰一下，请问去古镇怎么走？"],
    ["Local: Just keep going straight for about ten minutes.", "当地人：直走大概十分钟就到。"],
    ["Me: Straight ahead? Got it.", "我：一直往前走？明白了。"],
    ["Local: Then turn right at the clock tower. You can't miss it.", "当地人：到了钟楼右转，一眼就能看到。"],
    ["Me: Great. Is there a restroom nearby, by the way?", "我：太好了。对了，附近有洗手间吗？"],
    ["Local: Yes, in the visitor center, right over there.", "当地人：有的，游客中心里，就在那边。"],
    ["Me: Perfect. Thank you so much!", "我：太好了，太感谢了！"],
    ["Local: You're welcome. Enjoy your visit!", "当地人：不客气，祝你们玩得开心！"],
    ["Me: Kids, did you hear that? Straight, then right at the tower.", "我：孩子们，听到了吗？一直走，到钟楼右转。"],
    ["Kids: We heard! Let's go!", "孩子们：听到啦！快走吧！"],
  ]},

  /* ================= 突发状况 ================= */
  { id: 'oops-lost', cat: 'oops', emoji: '🔑', zh: '物品遗失', en: 'Lost Something', sents: [
    ["Me: Oh no, where's my wallet? It was right here!", "我：糟糕，我的钱包呢？刚才还在这儿！"],
    ["Honey: Calm down. When did you last see it?", "亲爱的：别急。你最后一次看到它是什么时候？"],
    ["Me: At the coffee shop, I think. I paid there.", "我：我想是在咖啡店，我在那儿付的钱。"],
    ["Honey: Call them and ask.", "亲爱的：打电话去问问。"],
    ["Me: Good idea. ... Hi, I think I left my wallet there.", "我：好主意。……你好，我的钱包好像落在你们店里了。"],
    ["Clerk: Let me check... Yes! A black wallet?", "店员：我看一下……有的！是个黑色钱包吗？"],
    ["Me: Yes! That's mine. I'll come by right away.", "我：对！是我的。我马上过去拿。"],
    ["Clerk: No problem. I'll keep it at the counter.", "店员：没问题，我放在收银台这里。"],
    ["Me: Thank you so much. You saved my day!", "我：太感谢了，你帮了我大忙！"],
    ["Honey: See? Panicking never helps.", "亲爱的：你看，着急也没用吧。"],
  ]},
  { id: 'oops-rain', cat: 'oops', emoji: '☔', zh: '突然下雨', en: 'Caught in the Rain', sents: [
    ["Emma: Mom, it's raining! We forgot our umbrellas!", "Emma：妈妈，下雨了！我们忘带伞了！"],
    ["Me: Oh no. Let's wait under that roof.", "我：糟糕。咱们到那个屋檐底下等一会儿。"],
    ["Leo: I'm getting wet!", "Leo：我被淋湿了！"],
    ["Me: Come here, hide under my jacket.", "我：快过来，躲到我的外套下面。"],
    ["Emma: Is it going to stop soon?", "Emma：雨会很快停吗？"],
    ["Me: The app says it'll pass in about ten minutes.", "我：软件上说大概十分钟就会停。"],
    ["Leo: I'm cold...", "Leo：我冷……"],
    ["Me: I know, buddy. Let's walk to that cafe and get something warm.", "我：我知道，宝贝。咱们走到那家咖啡馆，喝点热乎的。"],
    ["Emma: Good idea. Race you there!", "Emma：好主意。比比谁先跑到！"],
    ["Me: Hey, no running in the rain! Walk, please!", "我：嘿，下雨不许跑！走路过去！"],
  ]},
  { id: 'oops-broken', cat: 'oops', emoji: '💥', zh: '物件损坏', en: 'Something Got Broken', sents: [
    ["Emma: Mom... I broke your favorite mug. I'm sorry.", "Emma：妈妈……我把你最喜欢的杯子打碎了。对不起。"],
    ["Me: Oh... Are you hurt? That's what matters.", "我：哦……你没受伤吧？你没事才是最重要的。"],
    ["Emma: No, I'm okay. It just slipped out of my hand.", "Emma：没受伤，就是它从我手里滑掉了。"],
    ["Me: I see. Accidents happen. Just be more careful next time.", "我：我知道了。意外难免，下次小心一点就好。"],
    ["Emma: I'll buy you a new one with my pocket money.", "Emma：我用零花钱给你买个新的。"],
    ["Me: That's sweet of you. But you don't have to.", "我：你真贴心。不过不用啦。"],
    ["Emma: I want to. Really.", "Emma：我想买，真的。"],
    ["Me: Okay, deal. But first, let's clean this up carefully.", "我：好吧，那就这么说定了。不过咱们先把碎片小心收好。"],
    ["Emma: I'll get the broom.", "Emma：我去拿扫帚。"],
    ["Me: Good. Wear your slippers, not your socks.", "我：好。穿上拖鞋，别穿着袜子过来。"],
  ]},

  /* ================= 线上沟通 ================= */
  { id: 'onl-video', cat: 'online', emoji: '📹', zh: '亲戚视频通话', en: 'Video Call with Family', sents: [
    ["Aunt: Hello! Happy weekend! How is everyone?", "姑姑：哈喽！周末好呀！大家都好吗？"],
    ["Me: Hi, Auntie! We're all good. How about you?", "我：姑姑好！我们都挺好的。你怎么样？"],
    ["Aunt: Great! The weather here is lovely.", "姑姑：好得很！这边天气可好了。"],
    ["Me: That's nice. The kids want to say hi. Emma, Leo!", "我：那太好了。孩子们想跟你打招呼。Emma，Leo！"],
    ["Kids: Hi, Auntie!", "孩子们：姑姑好！"],
    ["Aunt: Oh my, you've grown so much!", "姑姑：哎呀，你们都长这么大了！"],
    ["Emma: Auntie, I got an A in English!", "Emma：姑姑，我英语考了 A！"],
    ["Aunt: Well done, Emma! You're so smart!", "姑姑：真棒，Emma！真聪明！"],
    ["Leo: Auntie, watch this! ...Did you see my trick?", "Leo：姑姑，你看我！……看到我的绝招了吗？"],
    ["Aunt: Haha, I saw it! Amazing!", "姑姑：哈哈，看到啦！太厉害了！"],
    ["Me: Okay, kids, let Auntie rest. Talk again next week!", "我：好啦孩子们，让姑姑休息。下周再聊！"],
    ["Aunt: Bye, everyone! Love you all!", "姑姑：拜拜！爱你们哟！"],
  ]},
  { id: 'onl-customer', cat: 'online', emoji: '🎧', zh: '联系线上客服', en: 'Contacting Customer Service', sents: [
    ["Me: Hi, my order hasn't arrived yet. It was due yesterday.", "我：你好，我的订单还没到，昨天就该送到了。"],
    ["Agent: I'm sorry about that. Could you give me your order number?", "客服：很抱歉。能告诉我您的订单号吗？"],
    ["Me: Sure, it's 88234567.", "我：好，88234567。"],
    ["Agent: Thanks. Let me check... It shows the package is still at the sorting center.", "客服：谢谢。我查一下……显示包裹还在分拣中心。"],
    ["Me: Really? That's strange. It shipped four days ago.", "我：真的吗？奇怪了，四天前就发货了。"],
    ["Agent: I apologize for the delay. There seems to be a backlog.", "客服：很抱歉给您带来了不便，那边好像积压了。"],
    ["Me: Okay. When can I expect it?", "我：好吧。那我什么时候能收到？"],
    ["Agent: It should arrive within two days. I'll flag it for priority delivery.", "客服：应该两天内到。我给您标记优先派送。"],
    ["Me: Alright. If it doesn't come, can I get a refund?", "我：行。要是还不到，能退款吗？"],
    ["Agent: Absolutely. Just contact us again and we'll process it right away.", "客服：当然可以。到时候再联系我们，我们马上处理。"],
    ["Me: Good to know. Thanks for your help.", "我：好的，谢谢你的帮助。"],
    ["Agent: You're welcome. Sorry again for the trouble!", "客服：不客气，再次抱歉给您添麻烦了！"],
  ]},
];
