/* =========================================================
   English Around You · 场景句库
   说明：每句格式 ["英文","中文"]，按场景分组。
   注意：后续新增句子请追加在场景末尾，不要插入中间，
        因为收藏的句子用「场景id:序号」定位。
   ========================================================= */

const CATS = [
  { id: 'family',    emoji: '👨‍👩‍👧', zh: '亲子家庭' },
  { id: 'driving',   emoji: '🚗',  zh: '开车出行' },
  { id: 'dining',    emoji: '🍽️', zh: '餐厅点餐' },
  { id: 'shopping',  emoji: '🛍️', zh: '购物消费' },
  { id: 'travel',    emoji: '✈️',  zh: '旅行途中' },
  { id: 'work',      emoji: '💼',  zh: '工作职场' },
  { id: 'social',    emoji: '👋',  zh: '社交往来' },
  { id: 'daily',     emoji: '🏠',  zh: '日常生活' },
  { id: 'health',    emoji: '💊',  zh: '健康就医' },
  { id: 'emergency', emoji: '🆘', zh: '紧急情况' },
];

const SCENARIOS = [
  /* ---------------- 亲子家庭 ---------------- */
  { id: 'family-morning', cat: 'family', emoji: '🌅', zh: '早晨起床', en: 'Morning Routine', sents: [
    ["Time to get up, sleepyhead!", "小懒虫，该起床啦！"],
    ["Good morning, sunshine!", "早上好，小太阳！"],
    ["Did you sleep well last night?", "昨晚睡得好吗？"],
    ["Hurry up, or we'll be late.", "快点，不然要迟到了。"],
    ["Brush your teeth and wash your face.", "刷牙洗脸。"],
    ["What do you want for breakfast?", "早餐想吃什么？"],
    ["Put on your jacket, it's chilly outside.", "穿上外套，外面有点凉。"],
    ["Did you pack your schoolbag?", "书包收拾好了吗？"],
    ["Don't forget your water bottle.", "别忘了带水杯。"],
    ["Let's go, I'll drop you off.", "走吧，我送你过去。"],
    ["Have a good day at school!", "在学校开心哦！"],
    ["See you this afternoon!", "下午见！"],
  ]},
  { id: 'family-meals', cat: 'family', emoji: '🍚', zh: '吃饭时间', en: 'Meal Time', sents: [
    ["Wash your hands before dinner.", "饭前要洗手。"],
    ["Dinner's ready! Come and eat!", "饭好啦，快来吃！"],
    ["Try a little bit, you'll like it.", "尝一口，你会喜欢的。"],
    ["Don't play with your food.", "不要玩食物。"],
    ["Eat your vegetables, they're good for you.", "吃蔬菜，对身体好。"],
    ["Do you want more rice?", "还要米饭吗？"],
    ["You're such a good eater!", "吃得真棒！"],
    ["No snacks before dinner.", "饭前不能吃零食。"],
    ["Use your spoon, not your hands.", "用勺子，不要用手抓。"],
    ["Chew slowly, there's no rush.", "慢点嚼，不着急。"],
    ["Help me clear the table.", "帮我收拾一下桌子。"],
    ["Who wants dessert?", "谁想吃甜点呀？"],
  ]},
  { id: 'family-homework', cat: 'family', emoji: '📚', zh: '学习与鼓励', en: 'Study & Encouragement', sents: [
    ["Did you finish your homework?", "作业做完了吗？"],
    ["Show me what you learned today.", "给我看看今天学了什么。"],
    ["Good job! I'm so proud of you.", "做得好！我为你骄傲。"],
    ["Try again, you can do it!", "再试一次，你能行！"],
    ["Don't give up so easily.", "别这么轻易放弃。"],
    ["It's okay to make mistakes.", "犯错没关系的。"],
    ["Focus, you're almost done.", "专心点，快做完了。"],
    ["If you need help, just ask me.", "需要帮助就叫我。"],
    ["You worked really hard today.", "你今天很努力。"],
    ["That's a beautiful drawing!", "画得真漂亮！"],
    ["Practice makes perfect.", "熟能生巧。"],
    ["Let's read a book together.", "我们一起读本书吧。"],
  ]},
  { id: 'family-bedtime', cat: 'family', emoji: '🌙', zh: '睡前时光', en: 'Bedtime', sents: [
    ["It's time for bed.", "该睡觉啦。"],
    ["Did you brush your teeth?", "刷牙了吗？"],
    ["Let's read a bedtime story.", "讲个睡前故事吧。"],
    ["Good night, sweet dreams!", "晚安，做个好梦！"],
    ["Give me a goodnight kiss.", "亲一个再说晚安。"],
    ["I'll leave the light on for a while.", "我给你留会儿灯。"],
    ["Sleep tight, see you tomorrow.", "好好睡，明天见。"],
    ["No iPad after bedtime.", "睡觉后不能看 iPad。"],
    ["Can you stay with me a little longer?", "你能再陪我一会儿吗？"],
    ["Dream of something nice.", "做个美美的梦哦。"],
  ]},

  /* ---------------- 开车出行 ---------------- */
  { id: 'driving-drive', cat: 'driving', emoji: '🚗', zh: '日常驾驶', en: 'Behind the Wheel', sents: [
    ["Fasten your seat belt, please.", "请系好安全带。"],
    ["Where are we headed?", "我们去哪儿？"],
    ["Turn left at the next intersection.", "下个路口左转。"],
    ["It's about a twenty-minute drive.", "开车大概二十分钟。"],
    ["Traffic is terrible today.", "今天堵车堵得厉害。"],
    ["We need to stop for gas.", "得去加点油了。"],
    ["Watch out for pedestrians.", "小心行人。"],
    ["The light is about to turn red.", "红灯要亮了。"],
    ["Take the next exit.", "从下个出口出去。"],
    ["I'm running a little late.", "我要晚到一会儿。"],
    ["Sorry, I got stuck in traffic.", "抱歉，路上堵车了。"],
    ["Can you read me the address again?", "再把地址给我念一遍好吗？"],
    ["Let's put on some music.", "放点音乐吧。"],
    ["We're almost there.", "我们快到了。"],
  ]},
  { id: 'driving-gas', cat: 'driving', emoji: '⛽', zh: '加油停车', en: 'Gas & Parking', sents: [
    ["Fill it up, please.", "请加满。"],
    ["Regular or premium?", "加普通还是高标号？"],
    ["How much is a gallon?", "一加仑多少钱？"],
    ["Can I pay by card?", "可以刷卡吗？"],
    ["Where's the nearest gas station?", "最近的加油站在哪儿？"],
    ["Can I park here?", "这里能停车吗？"],
    ["Is this spot taken?", "这个车位有人吗？"],
    ["Where's the parking lot?", "停车场在哪儿？"],
    ["How much is parking per hour?", "停车费一小时多少钱？"],
    ["I need a car wash, too.", "我还需要洗个车。"],
  ]},

  /* ---------------- 餐厅点餐 ---------------- */
  { id: 'dining-order', cat: 'dining', emoji: '🍽️', zh: '点餐与结账', en: 'Ordering & Paying', sents: [
    ["A table for two, please.", "请给我们一张两人桌。"],
    ["Can I see the menu, please?", "请给我看一下菜单。"],
    ["What do you recommend?", "您有什么推荐？"],
    ["I'll have the grilled salmon.", "我要烤三文鱼。"],
    ["Not too spicy, please.", "请不要太辣。"],
    ["Could I get some water, please?", "能给我倒点水吗？"],
    ["Is this dish vegetarian?", "这道菜是素的吗？"],
    ["We're ready to order.", "我们准备好点餐了。"],
    ["How long will it take?", "大概要等多久？"],
    ["Could we have the bill, please?", "请给我们结账。"],
    ["Can I get this to go?", "这个可以打包吗？"],
    ["It's delicious, thank you!", "很好吃，谢谢！"],
    ["I'm allergic to peanuts.", "我对花生过敏。"],
    ["Keep the change.", "不用找零了。"],
  ]},

  /* ---------------- 购物消费 ---------------- */
  { id: 'shopping-buy', cat: 'shopping', emoji: '🛍️', zh: '商场超市', en: 'Shopping', sents: [
    ["Excuse me, where can I find milk?", "请问牛奶在哪儿？"],
    ["How much is this?", "这个多少钱？"],
    ["Do you have this in a larger size?", "这个有大一号的吗？"],
    ["Can I try it on?", "我可以试穿吗？"],
    ["Is this on sale?", "这个在打折吗？"],
    ["That's a little expensive.", "有点贵。"],
    ["Can you give me a discount?", "能便宜一点吗？"],
    ["I'll take it.", "我买了。"],
    ["Do you accept credit cards?", "你们收信用卡吗？"],
    ["Could I have a receipt, please?", "能给我一张收据吗？"],
    ["I'd like to return this.", "我想退掉这个。"],
    ["There's something wrong with it.", "这个有点问题。"],
    ["I'm just looking, thanks.", "我随便看看，谢谢。"],
    ["Where is the checkout?", "收银台在哪儿？"],
  ]},

  /* ---------------- 旅行途中 ---------------- */
  { id: 'travel-airport', cat: 'travel', emoji: '🛫', zh: '机场登机', en: 'At the Airport', sents: [
    ["Where is the check-in counter?", "值机柜台在哪儿？"],
    ["I'd like a window seat, please.", "我想要一个靠窗的座位。"],
    ["How many bags can I check?", "我可以托运几件行李？"],
    ["Is my flight on time?", "我的航班准点吗？"],
    ["Which gate does my flight leave from?", "我的航班在哪个登机口？"],
    ["Where is gate B12?", "B12 登机口怎么走？"],
    ["I have a connecting flight.", "我要转机。"],
    ["Is there a delay?", "航班延误了吗？"],
    ["What time does boarding start?", "几点开始登机？"],
    ["Where is the baggage claim?", "行李提取处在哪里？"],
    ["My luggage is missing.", "我的行李不见了。"],
    ["Could you help me fill out this form?", "能帮我填一下这张表吗？"],
  ]},
  { id: 'travel-hotel', cat: 'travel', emoji: '🏨', zh: '酒店入住', en: 'At the Hotel', sents: [
    ["I'd like to check in, please.", "我要办理入住。"],
    ["Do you have any rooms available?", "还有空房吗？"],
    ["I have a reservation under Li.", "我用李的名字订了房。"],
    ["What time is breakfast?", "早餐几点开始？"],
    ["Could I have an extra towel?", "能再给我一条毛巾吗？"],
    ["The air conditioning isn't working.", "空调坏了。"],
    ["Could I check out late, please?", "我能延迟退房吗？"],
    ["I'd like to check out.", "我要退房。"],
    ["Can you call me a taxi?", "能帮我叫辆出租车吗？"],
    ["Is Wi-Fi free here?", "这里的 Wi-Fi 免费吗？"],
  ]},
  { id: 'travel-sight', cat: 'travel', emoji: '🗺️', zh: '问路与观光', en: 'Directions & Sightseeing', sents: [
    ["How do I get to the city center?", "去市中心怎么走？"],
    ["Is it far from here?", "离这里远吗？"],
    ["Can I walk there?", "走路能到吗？"],
    ["Which bus should I take?", "我该坐哪路公交？"],
    ["Can you take a photo for us?", "能帮我们拍张照吗？"],
    ["What time does the museum open?", "博物馆几点开门？"],
    ["How much is the entrance fee?", "门票多少钱？"],
    ["Where is a good restaurant nearby?", "附近有什么好吃的餐厅？"],
    ["I'm just here on vacation.", "我是来度假的。"],
    ["It's my first time here.", "这是我第一次来这里。"],
    ["This place is beautiful!", "这地方真美！"],
    ["Could you speak more slowly, please?", "您能说慢一点吗？"],
  ]},

  /* ---------------- 工作职场 ---------------- */
  { id: 'work-office', cat: 'work', emoji: '💼', zh: '办公室日常', en: 'Office Talk', sents: [
    ["Good morning, everyone.", "大家早上好。"],
    ["Did you have a good weekend?", "周末过得好吗？"],
    ["Let me get back to you on that.", "那件事我稍后回复你。"],
    ["Could you send me the report?", "能把报告发给我吗？"],
    ["Sorry to interrupt.", "抱歉打断一下。"],
    ["I'll take care of it.", "我来处理。"],
    ["That sounds like a great idea.", "这个主意真不错。"],
    ["I agree with you.", "我同意你的看法。"],
    ["I'm not so sure about that.", "这个我不太确定。"],
    ["Let's catch up over coffee sometime.", "有空一起喝杯咖啡聊聊。"],
    ["Have a great weekend!", "周末愉快！"],
    ["See you tomorrow.", "明天见。"],
  ]},
  { id: 'work-meeting', cat: 'work', emoji: '📊', zh: '会议沟通', en: 'Meetings', sents: [
    ["Shall we get started?", "我们开始吧？"],
    ["Let me share my screen.", "我共享一下屏幕。"],
    ["Could you speak a little louder?", "能说大声一点吗？"],
    ["Sorry, you're on mute.", "不好意思，你静音了。"],
    ["Let me write that down.", "我记一下。"],
    ["Can we reschedule the meeting?", "会议能改个时间吗？"],
    ["To sum up what we've discussed...", "总结一下我们刚才讨论的……"],
    ["Any questions or comments?", "有什么问题或意见吗？"],
    ["I have a question about the deadline.", "关于截止时间我有个问题。"],
    ["Let's follow up by email.", "我们邮件再跟进吧。"],
  ]},

  /* ---------------- 社交往来 ---------------- */
  { id: 'social-chat', cat: 'social', emoji: '☕', zh: '打招呼闲聊', en: 'Small Talk', sents: [
    ["How's it going?", "最近怎么样？"],
    ["Long time no see!", "好久不见！"],
    ["What have you been up to?", "最近在忙什么？"],
    ["This is my friend, Li Ming.", "这是我的朋友李明。"],
    ["Come in, make yourself at home.", "快进来，别客气。"],
    ["Would you like something to drink?", "想喝点什么？"],
    ["Help yourself!", "别客气，随便吃！"],
    ["How's your family?", "家人都好吗？"],
    ["What do you do for a living?", "你是做什么工作的？"],
    ["Do you come here often?", "你经常来这儿吗？"],
    ["Nice weather today, isn't it?", "今天天气不错，是吧？"],
    ["Let's keep in touch!", "保持联系！"],
  ]},
  { id: 'social-thanks', cat: 'social', emoji: '🙏', zh: '感谢与道歉', en: 'Thanks & Apologies', sents: [
    ["Thank you so much!", "太感谢了！"],
    ["Thanks a million!", "万分感谢！"],
    ["I really appreciate it.", "我非常感激。"],
    ["That's so kind of you.", "你真好。"],
    ["You saved my life!", "你真是帮了大忙！"],
    ["No, thank you!", "不用谢，该我谢谢你！"],
    ["I'm really sorry.", "真的很抱歉。"],
    ["It's all my fault.", "都是我的错。"],
    ["I didn't mean it.", "我不是故意的。"],
    ["No worries!", "没关系！"],
    ["That's quite all right.", "没什么，别放在心上。"],
    ["Please forgive me.", "请原谅我。"],
  ]},

  /* ---------------- 日常生活 ---------------- */
  { id: 'daily-phone', cat: 'daily', emoji: '📱', zh: '电话沟通', en: 'Phone Calls', sents: [
    ["Hello, this is Li Ming speaking.", "你好，我是李明。"],
    ["May I speak to Mr. Wang?", "请王经理接电话好吗？"],
    ["I'll call you back later.", "我稍后给你回电话。"],
    ["Sorry, I think you have the wrong number.", "抱歉，你可能打错了。"],
    ["The line is bad, could you repeat that?", "信号不好，能再说一遍吗？"],
    ["Can you hear me now?", "现在能听见吗？"],
    ["I'll text you the details.", "我把详细信息发给你。"],
    ["Could you take a message?", "能帮我捎个口信吗？"],
    ["I'll get back to you soon.", "我尽快回复你。"],
    ["Talk to you later. Bye!", "先这样，再见！"],
  ]},
  { id: 'daily-life', cat: 'daily', emoji: '🗓️', zh: '生活杂事', en: 'Daily Life', sents: [
    ["What's the weather like today?", "今天天气怎么样？"],
    ["What time is it now?", "现在几点了？"],
    ["Could you tell me the way to the station?", "请问去车站怎么走？"],
    ["How much longer will it take?", "还要多久？"],
    ["What does this word mean?", "这个单词什么意思？"],
    ["How do you say this in English?", "这个用英语怎么说？"],
    ["What time do you open?", "你们几点开门？"],
    ["What time do you close?", "你们几点关门？"],
    ["I'd like to make an appointment.", "我想预约一下。"],
    ["Just a moment, please.", "请稍等一下。"],
    ["I'll take care of it right away.", "我马上处理。"],
    ["See you around!", "回头见！"],
  ]},

  /* ---------------- 健康就医 ---------------- */
  { id: 'health-doctor', cat: 'health', emoji: '🏥', zh: '看病就医', en: 'At the Doctor', sents: [
    ["I don't feel well.", "我不太舒服。"],
    ["I have a headache.", "我头疼。"],
    ["I've had a fever since yesterday.", "我从昨天开始发烧。"],
    ["Where does it hurt?", "你哪里疼？"],
    ["It hurts right here.", "就这里疼。"],
    ["I have a sore throat and a runny nose.", "我嗓子疼，还流鼻涕。"],
    ["How long have you felt this way?", "这样持续多久了？"],
    ["Are you allergic to any medicine?", "你对什么药物过敏吗？"],
    ["Take this medicine twice a day.", "这药一天吃两次。"],
    ["Get some rest and drink plenty of water.", "多休息，多喝水。"],
    ["Do I need a follow-up visit?", "我需要复诊吗？"],
    ["I need a doctor's note.", "我需要一张病假条。"],
  ]},

  /* ---------------- 紧急情况 ---------------- */
  { id: 'emergency-now', cat: 'emergency', emoji: '🆘', zh: '紧急求助', en: 'Emergency', sents: [
    ["Help!", "救命！"],
    ["Call the police!", "快报警！"],
    ["Call an ambulance, please!", "请叫救护车！"],
    ["I need a doctor, now!", "我需要医生，快点！"],
    ["It's an emergency.", "情况紧急。"],
    ["Where is the nearest hospital?", "最近的医院在哪儿？"],
    ["I lost my passport.", "我的护照丢了。"],
    ["My wallet was stolen.", "我的钱包被偷了。"],
    ["My car broke down.", "我的车抛锚了。"],
    ["Can you help me, please?", "求求你帮帮我。"],
  ]},
];
